### ISSUE TITLE
Time Tracking Inaccurate

### ISSUE THREAD

**Issue by timeowilliams** [timeowilliams/deepFocus#12]
### Describe the bug

<img width="723" alt="Screenshot 2024-10-03 at 9 51 10 AM" src="https://github.com/user-attachments/assets/1fd7b15e-8fb1-454e-bee0-3f4bf1ee032e">
<img width="273" alt="Screenshot 2024-10-03 at 9 52 35 AM" src="https://github.com/user-attachments/assets/a7d1abd0-a28f-4283-86f5-1d1d5cd73ec9">

Despite it being 9:51 AM in the morning, the deepFocus app is saying that i've done 21 hours of deep work on Thursday. 

```bash

Creating new tracker
tracker is  {
  url: 'Weekly Priorities for Goals',
  title: 'Weekly Priorities for Goals',
  timeSpent: 0,
  lastActiveTimestamp: 1727922043452
}
Ignoring Apple App com.apple.loginwindow
System idle for 162 seconds.
System idle for 282 seconds.
System idle for 402 seconds.
System idle for 522 seconds.
System idle for 642 seconds.
System idle for 762 seconds.
System idle for 882 seconds.
System idle for 1002 seconds.
System idle for 1122 seconds.
System idle for 1242 seconds.
System idle for 1362 seconds.
System idle for 1482 seconds.
System idle for 1602 seconds.
System idle for 1722 seconds.
System idle for 1842 seconds.
Received event for fetch-deep-work-data
Worker received message: {
  type: 3,
  data: {
    deepWorkHours: {
      Monday: 0,
      Tuesday: 0,
      Wednesday: 9.54,
      Thursday: 0,
      Friday: 0,
      Saturday: 0,
      Sunday: 0
    },
    currentSiteTimeTrackers: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ]
  }
}
Not deep work Finder
Not deep work https://www.tldraw.com
Not deep work https://x.com
Not deep work https://plausible.io
Not deep work https://www.solidjs.com
Not deep work https://tailwindcss.com
Not deep work Tech-Nest-Ventures/get-windows: Get metadata about the active window and open windows (title, id, bounds, owner, etc)
Not deep work get-windows/Sources at main · rize-io/get-windows
Not deep work Open
Not deep work timeo (@timeowilliams) / X
Not deep work Merge pull request #11 from Tech-Nest-Ventures/add-circular-chart · Tech-Nest-Ventures/deepFocus@a0899bb
Not deep work Facebook
Not deep work Gmail
Not deep work Our Work - Liftoff
Not deep work Milly Barker 🌱 (@drmillybarker) / X
Not deep work Tony Dinh 🎯 on X: "8 hours of quality work is a lot when I still had a job, an 8-hour workday was more like 1.5 hours of real work the amount of inefficiency that big companies are willing to accept is insane" / X
Not deep work Newsletter - Marketing Letter
Not deep work Tech-Nest-Ventures/deepFocus: building the "oura" for work
Not deep work feat: add circular chart in Home page for users to see current progress
Not deep work Master
Not deep work Deno 2.0 Release Candidate
Not deep work How many of you are using Deno in production for your business or side project? : r/Deno
Not deep work Deno.js in production. Key takeaways. | by Steven de Salas | Medium
Not deep work Deno 2 vs Bun? What are your thoughts? : r/Deno
Not deep work Deno - A secure TypeScript runtime on V8
Not deep work Deno is supporting NPM, what is stopping Node developers Now? : r/node
Not deep work Rust vs. Go NO, it's Rust and Go. : r/golang
Not deep work Rust vs. Go in 2023
Not deep work Why Discord is switching from Go to Rust
Not deep work Speed of Go vs Rust in practice/real world experience? : r/rust
Not deep work Rust Programming Language
Not deep work Home / X
Not deep work deno dependency
Not deep work Discord
totalDeepWorkTime 34350569
timeSpentInHours 9.541824722222222
Deep work hours for Thursday: 9.54 hours
Current deep work hours: 9.54 hours
Worker Message: {
  type: 3,
  data: {
    Monday: 0,
    Tuesday: 0,
    Wednesday: 9.54,
    Thursday: 9.54,
    Friday: 0,
    Saturday: 0,
    Sunday: 0
  }
}
```

Inflation is definitely happening because I am running two separate Electron instances of deepWork (one as an Application & the other in dev) 

However, the fact that we set Thursday to have the same # of deep work hours as Wednesday means that there's some error in the Date & reset logic. 

### Used Scaffolding

create-electron

### Used Package Manager

pnpm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.
